name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.9.9"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E402,F841,F401,E302,E305,W291,W605"
          max-line-length: "200"